environment:
  matrix:
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2022
      CMAKE_GENERATOR: Visual Studio 17 2022
      MPI_HOME: "C:/Program Files (x86)/Microsoft SDKs/MPI"

artifacts:
  - path: build\perf_stat_dir
    name: perf_stat_dir

install:
  - ps: Start-FileDownload 'https://github.com/microsoft/Microsoft-MPI/releases/download/v10.1.1/msmpisetup.exe'
  - MSMpiSetup.exe -unattend
  - set PATH=C:\Program Files\Microsoft MPI\Bin;%PATH%
  - ps: Start-FileDownload 'https://github.com/microsoft/Microsoft-MPI/releases/download/v10.1.1/msmpisdk.msi'
  - msmpisdk.msi /passive

build_script:
  - cmd: git submodule update --init --recursive
  - cmd: mkdir build
  - cmd: cmake -G "%CMAKE_GENERATOR%" -S . -B build ^
               -D USE_SEQ=ON   ^
               -D USE_MPI=ON   ^
               -D USE_OMP=ON   ^
               -D USE_TBB=ON   ^
               -D USE_STL=ON   ^
               -D USE_FUNC_TESTS=OFF  ^
               -D USE_PERF_TESTS=ON   ^
               -D CMAKE_BUILD_TYPE=RELEASE   ^
               -D MPI_C_INCLUDE_PATH:PATH="%MPI_HOME%/Include" ^
               -D MPI_C_LIBRARIES:PATH="%MPI_HOME%/Lib/x64/msmpi.lib" ^
               -D MPI_CXX_INCLUDE_PATH:PATH="%MPI_HOME%/Include" ^
               -D MPI_CXX_LIBRARIES:PATH="%MPI_HOME%/Lib/x64/msmpi.lib"
  - cmd: cmake --build build --config Release --parallel
  - cmd: scripts/generate_perf_results.bat
