ignore:
  - "**/perf_tests/**"
  - "**/func_tests/**"
  - "**/all/runner.cpp"
  - "**/mpi/runner.cpp"
  - "**/omp/runner.cpp"
  - "**/seq/runner.cpp"
  - "**/stl/runner.cpp"
  - "**/tbb/runner.cpp"
coverage:
  status:
    project:
      default:
        threshold: 1%
    patch:
      default:
        threshold: 5%
