ignore:
  - "**/tasks/**/tests/**"
  - "**/tasks/common/runners/**"
  - "**/modules/core/util/include/func_test_util.hpp"
  - "**/modules/core/util/include/perf_test_util.hpp"
coverage:
  status:
    project:
      default:
        threshold: 1%
    patch:
      default:
        threshold: 5%
