name: Build application

on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, edited, synchronize, reopened]
  merge_group:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: >-
    ${{ github.ref != 'refs/heads/master' &&
        github.event_name != 'merge_group' &&
        !startsWith(github.ref, 'refs/heads/gh-readonly-queue') }}

jobs:
  pr_compliance:
    uses: ./.github/workflows/pr-compliance.yml

  pre-commit:
    needs: [pr_compliance]
    uses: ./.github/workflows/pre-commit.yml
  ubuntu:
    needs:
      - pre-commit
    uses: ./.github/workflows/ubuntu.yml
  mac:
    needs:
      - pre-commit
    uses: ./.github/workflows/mac.yml
  windows:
    needs:
      - pre-commit
    uses: ./.github/workflows/windows.yml
  perf:
    needs:
      - ubuntu
      - mac
      - windows
    uses: ./.github/workflows/perf.yml

  pages:
    needs:
      - perf
    uses: ./.github/workflows/pages.yml
