name: Build application

on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, edited, synchronize, reopened]
  merge_group:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: >-
    ${{ github.ref != 'refs/heads/master' &&
        github.event_name != 'merge_group' &&
        !startsWith(github.ref, 'refs/heads/gh-readonly-queue') }}

jobs:
  pr_title:
    name: PR Title Gate
    runs-on: ubuntu-latest
    steps:
      - name: Non-PR event — skip title validation
        if: ${{ github.event_name != 'pull_request' }}
        run: echo "Not a PR event; skipping title check"

      - name: Checkout
        if: ${{ github.event_name == 'pull_request' }}
        uses: actions/checkout@v4

      - name: Set up Python
        if: ${{ github.event_name == 'pull_request' }}
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Validate PR title
        if: ${{ github.event_name == 'pull_request' }}
        run: python .github/scripts/validate_pr.py

  pre-commit:
    if: ${{ github.event_name != 'pull_request' || github.event.action != 'edited' || github.event.changes.title }}
    needs:
      - pr_title
    uses: ./.github/workflows/pre-commit.yml
  ubuntu:
    if: ${{ github.event_name != 'pull_request' || github.event.action != 'edited' || github.event.changes.title }}
    needs:
      - pre-commit
    uses: ./.github/workflows/ubuntu.yml
  mac:
    if: ${{ github.event_name != 'pull_request' || github.event.action != 'edited' || github.event.changes.title }}
    needs:
      - pre-commit
    uses: ./.github/workflows/mac.yml
  windows:
    if: ${{ github.event_name != 'pull_request' || github.event.action != 'edited' || github.event.changes.title }}
    needs:
      - pre-commit
    uses: ./.github/workflows/windows.yml
  perf:
    if: ${{ github.event_name != 'pull_request' || github.event.action != 'edited' || github.event.changes.title }}
    needs:
      - ubuntu
      - mac
      - windows
    uses: ./.github/workflows/perf.yml

  pages:
    if: ${{ github.event_name != 'pull_request' || github.event.action != 'edited' || github.event.changes.title }}
    needs:
      - perf
    uses: ./.github/workflows/pages.yml
